### ISSUE TITLE
.7z cannot be decompressed correctly after downloading

### ISSUE THREAD

**Issue by bingling00** [bananakid/xnviewmp-w10-qss#1]
.7z cannot be decompressed correctly after downloading.

**Comment by bananakid** [comment]
Please double-check if MD5 checksum of the file you downloaded `Windows 10 Light Mode Theme 0.1.1 for XnView MP 0.98.1` is `56 92 51 be a9 0c 36 ca dd 8c 28 69 1f 2f 5e 0a` (that will verify your 7z file is not corrupted) using Windows Command Prompt command `CertUtil -hashfile "%UserProfile%\Downloads\Windows 10 Light Mode Theme 0.1.1 for XnView MP 0.98.1.7z" MD5` (if 7z file is located in your Downloads folder). Please use [official 7-Zip open source software](https://www.7-zip.org/download.html) 19.00 or later or [Archive Extractor Online service](https://extract.me/) to extract 7z archive.

**Comment by bingling00** [comment]
Thank you. I made a mistake in downloading. Now the decompression is successful
